language: python
python:
  - "3.11"
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: elasticbeanstalk
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: AWS_BUCKET_NAME
  edge: true # opt in to dpl v2