language: python
python:
  - "3.13"
install:
  - pip install -r requirements.txt
# Run format, lint, and test coverage checks here
script:
  - flake8 .                      # Check for linting errors first
  - black --check .               # Check for formatting errors
  - coverage run -m pytest        # Run tests under coverage

# This command runs ONLY if the script section passes
after_success:
  - coveralls                     # Report coverage results
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  bucket: $AWS_BUCKET_NAME
  app: first-django-app-4
  env: first-django-app-4-dev
  edge: true # opt in to dpl v2
  on:
    branch: main